
export interface Message {
  type: MessageType;
  data: unknown;
}
export enum MessageType {
  REQUEST_CUSTOMCARDS_FROM_CONTENT = 'REQUEST_CUSTOMCARDS_FROM_CONTENT',
  SEND_DETECTED_CARDS = 'SEND_DETECTED_CARDS',
  REQUEST_DETECTED_CARDS_FROM_PANEL = 'REQUEST_DETECTED_CARDS_FROM_PANEL',
  REQUEST_DETECTED_CARDS_TO_CONTENT = 'REQUEST_DETECTED_CARDS_TO_CONTENT',
  ENTER_INSPECTION_MODE_FROM_PANEL = 'ENTER_INSPECTION_MODE_FROM_PANEL',
  SET_INSPECTION_TAB_ID = 'SET_INSPECTION_TAB_ID',
  EXIT_INSPECTION_MODE_FROM_PANEL = 'EXIT_INSPECTION_MODE_FROM_PANEL',
  SEND_INSPECTION_DATA_FROM_CONTENT = 'SEND_INSPECTION_DATA_FROM_CONTENT',
  CHANGE_LANGUAGE = 'CHANGE_LANGUAGE'
}

export enum PortNames {
  ENTER_INSPECTION_MODE_FROM_PANEL = 'ENTER_INSPECTION_MODE_FROM_PANEL',
  READY_INSPECTION_MODE_FROM_CONTENT = 'READY_INSPECTION_MODE_FROM_CONTENT',
}

